### ISSUE TITLE
Return value.toString() from KeyValueStructuredArgument.toString()

### ISSUE THREAD

**Issue by rsassoon** [quarkiverse/quarkus-logging-json#142]
When outputting logs locally we would disable json formatting and still would want to see the structured values in the logged message, e.g.,:

```
log.info("Test log of structured arg with value {}", kv("key", "value"));
``` 

Please override `toString()` in [KeyValueStructuredArgument](https://github.com/quarkiverse/quarkus-logging-json/blob/cac370b8c2fd3ed015497715b346cd31e21a238b/runtime/src/main/java/io/quarkiverse/loggingjson/providers/KeyValueStructuredArgument.java) to return `value.toString()`

**Comment by SlyngDK** [comment]
There is no good solution when you have disabled the extension.

Only possible solution will be some string formatting, as there is no json generator available and trying to keep this extension small and without too many dependencies.
There will be too many opinions on this formatting, I think the best solution will be to extend `KeyValueStructuredArgument` with your own implementation and use that.
