### ISSUE TITLE
Document changes for new releases

### ISSUE THREAD

**Issue by rubensa** [quarkiverse/quarkus-logging-json#205]
I updated from **1.1.1** to **2.0.0** and then started to receive many "**Unrecognized configuration key**" warnings.

I realized that there was a [change](https://github.com/quarkiverse/quarkus-logging-json/commit/2eec8fb303e97539572573b0cf9d9081a133cb44#diff-ebc812c9dbe2541fd37a59e692d8a3cf43345ac48ca449f995a5204379e57332R10) in configuration properties base path from "**log.console.json**" to "**log.json**" so I had to update all my configuration properties.

It would be very helpful if this kind of changes are documented in the [release notes](https://github.com/quarkiverse/quarkus-logging-json/releases/tag/2.0.0).

**Comment by SlyngDK** [comment]
I have created a release note, hope that help others a little in the future.

Your are welcome to contribute a migration text, and I will add it to the release note.
