### ISSUE TITLE
Unable to create new CustomLogHandler

### ISSUE THREAD

**Issue by marek-mizera** [quarkiverse/quarkus-logging-json#213]
Hi

from readme.md adding new CustomLogHandler for creating new field looks easy.
But, when I add quarkus-logging-json dependency, there is no "io.quarkiverse.loggingjson.JsonProvider" interface available.

quarkus version is currently 2.9.2.FINAL, we will be upgrading soon, but not sure if that is relevant to this.

**Comment by SlyngDK** [comment]
Are you sure you are using correct dependency, have changed in early versions.
```
<dependency>
  <groupId>io.quarkiverse.loggingjson</groupId>
  <artifactId>quarkus-logging-json</artifactId>
  <version>2.0.0</version>
</dependency>
```
