### ISSUE TITLE
How is this extension different from io.quarkus:quarkus-logging-json?

### ISSUE THREAD

**Issue by Manfred73** [quarkiverse/quarkus-logging-json#220]
Hi,

Not really a bug, but a question. As the title says, what's the difference between this extension and the one from io.quarkus?
Currently I'm using the one from quarkiverse because I want to do structured logging. Does the one from io.quarkus also support this?

**Comment by SlyngDK** [comment]
@Manfred73 This extension is created because default extension, was not supporting structured logging. I am not aware what changes made to the default, after I created this extension.
