### ISSUE TITLE
Ignore some MDC fields

### ISSUE THREAD

**Issue by Sukitly** [quarkiverse/quarkus-logging-json#230]
Hi, I am new to this library.
I got a question:
What should I do to ignore some MDC fields when using ths library?
Is there any way to do it now?

Thanks.

**Comment by SlyngDK** [comment]
@Sukitly No there is no filtering of MDC fields, but you can disable MDC logging, and implement your own https://github.com/quarkiverse/quarkus-logging-json#custom-log-handler.

All config options can be seen here https://quarkiverse.github.io/quarkiverse-docs/quarkus-logging-json/dev/index.html
