### ISSUE TITLE
GELF format

### ISSUE THREAD

**Issue by ericsouza** [quarkiverse/quarkus-logging-json#259]
Hi, thanks for this extensions!!

Is there any way to modify the format to use the GELF format? I use Graylog as my log manager but collecting the logs direct from pods in my k8s cluster. 

Something similar to what was done with `Elastic Common Scheme` and maybe add a property like: `quarkus.log.json.log-format=gelf` would be amazing

**Comment by SlyngDK** [comment]
I don't know the gelf format or graylog, is it JSON and there is a well designed schema, you are welcome to add formatter.

But I think I have seen another quarkus extension for gelf, maybe you are looking for that.

**Comment by marcelstoer** [comment]
As there's an [official GELF extension](https://quarkus.io/extensions/io.quarkus/quarkus-logging-gelf/) I propose to close this issue.
