### ISSUE TITLE
io.quarkiverse.jsonlogging - log format is ignored

### ISSUE THREAD

**Issue by GinaGeorgescul** [quarkiverse/quarkus-logging-json#267]
Hello,
I am using the 
```
<dependency>
<groupId>io.quarkiverse.loggingjson</groupId>
<artifactId>quarkus-logging-json</artifactId>
<version>2.0.1</version>
</dependency> 
```
extension in my logging library in order to have json formatted logs.
I have also added a custom provider for masking sensitive information and renaming some fields.
I notice that the logs regarding startup time, the profile activated etc are not formatted. Eg:
```
%s%s stopped in %ss
%s %s %s (powered by Quarkus %s) started in %ss. %s 
Profile%s %s activated. %s
```

When debugging I see that the information is there, however the issue is that the format style is "MESSAGE_FORMAT" (so it doesn't replace the %s)

Do you have any idea about how I could solve this?

**Comment by GinaGeorgescul** [comment]
The problem was my custom provider

**Comment by venkata-malepati** [comment]
@GinaGeorgescul I'm facing same problem in my application. In debugging I see that the information is there, however the issue is that the format style is "MESSAGE_FORMAT" (so it doesn't replace the %s). please clarify what is "problem was my custom provider"? can you provider more info?
