### ISSUE TITLE
Create AsciiDoc

### ISSUE THREAD

**Issue by SlyngDK** [quarkiverse/quarkus-logging-json#63]
Create documentation in asciidoc for use on the quarkiverse documentation site.

**Comment by gsmet** [comment]
@SlyngDK https://github.com/quarkiverse/quarkiverse-github-app/tree/master/docs might be a good inspiration if you want to set up some documentation.

**Comment by SlyngDK** [comment]
@gsmet Do you have some docs how this is working and how to test?
The first thing that is important for me, is getting config in docs, but how to do this automatic?

**Comment by gsmet** [comment]
@SlyngDK sorry, I missed your ping somehow. I will create a pull request with the doc infrastructure we have generalized and added to the template. It should make things easier for you.
