### ISSUE TITLE
TimestampJsonProvider don't implement Enabled

### ISSUE THREAD

**Issue by lthasle** [quarkiverse/quarkus-logging-json#77]
It would be nice if the class: TimestampJsonProvider also could implement Enabled
In order to get rid of the long timestamp format for local development.
This currently does not work:
%dev.quarkus.log.console.json.fields.timestamp.enabled=false

**Comment by SlyngDK** [comment]
This feature is getting available in version 0.3.1.

**Comment by lthasle** [comment]
works great!
