### ISSUE TITLE
Complex transformations

### ISSUE THREAD

**Issue by dfa1** [quarkiverse/quarkus-logging-json#82]
@gsmet  hello :)

Let's discuss here (https://github.com/quarkusio/quarkus/issues/15193):

In our quarkus apps we are required to provide additional metadata for every log event. 

Example
Given the following payload [1]:
```
{
  "timestamp":"2021-02-19T18:00:53Z",
  "sequence":3219,
  "loggerClassName":"database.BlockCacheBuilder",
  "loggerName":"BlockCacheBuilder",
  "level":"INFO",
  "logMessage":"Block cache: Creating Clock Cache with 2147483648 capacity",
  "threadName":"executor-thread-1",
  "threadId":71,
  "mdc":{},
  "ndc":"",
  "hostName":"n36771",
  "processName":"MyApplication",
  "processId":22208
}
```

the requirement would be to enrich it with:
```
{
  "EventObject":"1.2",
  "eventTimestamp":"2021-02-19T18:00:53Z",
  "header":{"eventCategory":"SEC","eventMessage":"Security event","severityLevel":"INFO"},
  "product":{"productName":"MyApp","applicationId":"A0666","componentId":"A0666.001","productVersion":"15.1.3-SNAPSHOT","productVendor":"SIX"}, <--- product configuration in application.yaml
  "origin":{"environment":"prod","hostname":"n36771","processId":"22208","threadId":"71"}, <-- hostname is coming from payload (org.jboss.logmanager.formatters.StructuredFormatter)
  "eventPayload": <--- literal payload here (see [1]) 
}
```

Would be possible to achieve this by using this library?
Additional requirements are:
- ability to rename log levels: "SEVERE" -> "ERROR", "WARN" -> "WARNING"
- copy some attributes from the event payload to the external message

**Comment by SlyngDK** [comment]
Hi @dfa1 

There are multiple ways, as you can see in the `README.md` there are Structured Argument and Creating your own `JsonProvider`.

If your are have a object to day, it can just implement `io.quarkus.logging.json.structured.StructuredArgument`, and log it as part of the logging arguments. It will be picked up by `ArgumentsJsonProvider`, and you write the json in the format you like.

The other solution is to create a custom log handler like [here](https://github.com/quarkiverse/quarkus-logging-json#custom-log-handler). And you can get your data from `ExtLogRecord`, and log it as you like it.

You can disable the logging of the default level field in config, and implement it by your self.

I hope you can use this answer.

**Comment by dfa1** [comment]
hi @SlyngDK, 

thank you, oh I missed that completely 😮 

Yes, this is exactly what I need! The only point missing point is that I should access the `org.slf4j.Marker` (see https://github.com/jboss-logging/jboss-logmanager/pull/333).
