### ISSUE TITLE
Write Log to a file

### ISSUE THREAD

**Issue by bollerdominik** [quarkiverse/quarkus-logging-json#87]
Thanks for this library.
Is there any way I can use it to write the logs to a log file? Unfortunately, Quarkus does not currently provide a way to write JSON to a log file.

**Comment by SlyngDK** [comment]
Hi @bollerdominik This library is providing a log format, picked up by quarkus and used. This functionally is not done for file logging, so this will require changes to the quarkus project.

Maybe @gsmet can help.

**Comment by SlyngDK** [comment]
I am closing this, because this is something quarkus need to add support for.
This extension is already providing a log formatter ready to be used for that purpose also.
