### ISSUE TITLE
Transfer the Quarkiverse sonarcloud.io organization to Quarkiverse admins

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-logging-json#88]
Hey!

We'd like to enable SonarCloud.io in the GitHub, however I need you to transfer the ownership in https://sonarcloud.io/organizations/quarkiverse/ to us (add @gastaldi and @gsmet as admins)

**Comment by SlyngDK** [comment]
Sounds great, I have added yours user's.
